---
abstract: 'Agile standup bot ala tender'
author:
  - 'Hyungsuk Hong <aanoaa@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300026, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hubot-Scripts-standup
requires:
  DateTime: 0
  JSON::XS: 0
  List::Util: 0
  strict: 0
  warnings: 0
version: 0.0.1
